# Polybar Pulseaudio Control
["pulseaudio-control"]
    type = "file"
    url = "https://raw.githubusercontent.com/marioortizmanero/polybar-pulseaudio-control/master/pulseaudio-control"
    executable = true
    refreshPeriod = "168h"