[window]
opacity = 0.97
blur = true
# macOS: Use Option as Meta key for tmux-tilish and other Alt/Meta bindings
# Note: This option is ignored on Linux/Windows
option_as_alt = "Both"

[font]
size = 14.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[general]
import = ["~/.config/alacritty/themes/themes/ayu_light.toml"]

[terminal]
# OSC 52 clipboard support - allows remote/tmux to write to local clipboard
osc52 = "CopyPaste"

# Ctrl+Alt bindings for tmux-tilish/Zellij via Kanata = layer
# CSI u format: \x1b[{ascii};{mod}u where mod=7 for Ctrl+Alt, mod=8 for Ctrl+Alt+Shift
# https://github.com/alacritty/alacritty/issues/93

# Shift+Return and Ctrl+Return
[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

# Navigation: =+hjkl
[[keyboard.bindings]]
chars = "\u001B[104;7u"
key = "H"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[106;7u"
key = "J"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[107;7u"
key = "K"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[108;7u"
key = "L"
mods = "Control|Alt"

# Tabs/Windows: =+1-9, =+0
[[keyboard.bindings]]
chars = "\u001B[49;7u"
key = "1"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[50;7u"
key = "2"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[51;7u"
key = "3"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[52;7u"
key = "4"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[53;7u"
key = "5"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[54;7u"
key = "6"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[55;7u"
key = "7"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[56;7u"
key = "8"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[57;7u"
key = "9"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[48;7u"
key = "0"
mods = "Control|Alt"

# Window actions: =+q, =+z, =+f
[[keyboard.bindings]]
chars = "\u001B[113;7u"
key = "Q"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[122;7u"
key = "Z"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[102;7u"
key = "F"
mods = "Control|Alt"

# Layouts: =+s, =+S, =+v, =+V, =+t, =+r
[[keyboard.bindings]]
chars = "\u001B[115;7u"
key = "S"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[115;8u"
key = "S"
mods = "Control|Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[118;7u"
key = "V"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[118;8u"
key = "V"
mods = "Control|Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[116;7u"
key = "T"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[114;7u"
key = "R"
mods = "Control|Alt"

# Window management: =+n (rename), =+e (detach), =+c (reload)
[[keyboard.bindings]]
chars = "\u001B[110;7u"
key = "N"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[101;8u"
key = "E"
mods = "Control|Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[99;8u"
key = "C"
mods = "Control|Alt|Shift"

# Move pane to window: =+Shift+1-9
[[keyboard.bindings]]
chars = "\u001B[49;8u"
key = "1"
mods = "Control|Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[50;8u"
key = "2"
mods = "Control|Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[51;8u"
key = "3"
mods = "Control|Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[52;8u"
key = "4"
mods = "Control|Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[53;8u"
key = "5"
mods = "Control|Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[54;8u"
key = "6"
mods = "Control|Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[55;8u"
key = "7"
mods = "Control|Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[56;8u"
key = "8"
mods = "Control|Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[57;8u"
key = "9"
mods = "Control|Alt|Shift"

# Splits: =+-, =+\, =+Space, =+Tab
[[keyboard.bindings]]
chars = "\u001B[45;7u"
key = "Minus"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[92;7u"
key = "Backslash"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[32;7u"
key = "Space"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[9;7u"
key = "Tab"
mods = "Control|Alt"

# New pane: =+" (Ctrl+Alt+Shift+')
[[keyboard.bindings]]
chars = "\u001B[39;8u"
key = "'"
mods = "Control|Alt|Shift"

# Resize: =+= (grow left), =++ (grow down), =+_ (grow up)
[[keyboard.bindings]]
chars = "\u001B[61;7u"
key = "Equals"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[43;8u"
key = "Equals"
mods = "Control|Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[95;8u"
key = "Minus"
mods = "Control|Alt|Shift"
