[window]
opacity = 0.97
blur = true
# macOS: Use Option as Meta key for tmux-tilish and other Alt/Meta bindings
# Note: This option is ignored on Linux/Windows
option_as_alt = "Both"

[general]
import = [
    "~/.config/alacritty/themes/themes/ayu_light.toml"
]

# Instead of using: `alacritty --print-events`
# https://github.com/alacritty/alacritty/wiki/Keyboard-mappings#how-to-create-a-mapping
# Open a terminal without Tmux, and get the key you want with the command:
#
# ```sh
# nix-shell -p unixtools.xxd
# xxd -psd
# ```

# https://github.com/jackMort/ChatGPT.nvim/issues/99#issuecomment-1492668722
# https://stackoverflow.com/a/42461580/609025
[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"
