sourceDir = "~/.local/share/chezmoi"

[diff]
command = "delta"
args = ["--side-by-side", "--syntax-theme", "Catppuccin-mocha"]

[merge]
command = "nvim -d"

[git]
# Disabled because we use claude_chain in run_before script
autoCommit = false
autoPush = false
